[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:queue-worker]
command=php artisan queue:work --tries=3 --timeout=90
directory=/var/www/template-laravel-docker
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/template-laravel-docker/storage/logs/queue.log

[program:horizon]
process_name=%(program_name)s
command=php /var/www/template-laravel-docker/artisan horizon
autostart=true
autorestart=true
user=www
redirect_stderr=true
stdout_logfile=/var/www/template-laravel-docker/storage/logs/horizon.log

